spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-161.railway.app:6554/railway
    username: postgres
    password: O60zGqsjomuTKKkPmx00
    name: railway
  jpa:
   generate-ddl: true
   hibernate:
    ddl-auto: update
