spring:
  datasource:
    url: ${DBURL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    name: railway
  jpa:
   generate-ddl: true
   hibernate:
    ddl-auto: update
  kafka:
   bootstrap-servers: kafka.railway.internal:29092
   consumer:
    group-id: traveler-kafka-group

